### ISSUE TITLE
Wrong number of pomodori, when there is no long break

### ISSUE THREAD

**Issue by hryniuk** [okraits/omodoro#10]
If I see correctly, `cnt_pomodori` is initialized with default value of `num_pomodori` and it's changed to correct value only when long break is over. So, when **omodoro** is called with `1-1-1-1` there are still four pomodori in the cycle.

**Comment by okraits** [comment]
Yes, you are right. The issue is fixed in https://github.com/okraits/omodoro/commit/ba8867801cf42bc50d9615a9a5cc39299fcb6d88.

Thank you very much for reporting the issue and sorry for responding to this with such a huge delay.

**Comment by hryniuk** [comment]
Well done :).

**Comment by okraits** [comment]
Thanks :-) Well, it was an easy and obvious one :-)
